export const RAW_DATA = [
    {
        "mes_nome": "Jan",
        "mes_num": 1,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": -0.06,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 89.25 – R$ 207.79",
        "n_obs_mes": 93,
        "r_quadrado_mes": 0.92,
        "faixa_praticada_MES_R$_duracao": "R$ 43.55 – R$ 188.90"
    },
    {
        "mes_nome": "Jan",
        "mes_num": 1,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": 0.05,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 36.96 – R$ 372.26",
        "n_obs_mes": 44,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 36.96 – R$ 372.26"
    },
    {
        "mes_nome": "Jan",
        "mes_num": 1,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": 0.13,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 23.09 – R$ 81.60",
        "n_obs_mes": 68,
        "r_quadrado_mes": 0.82,
        "faixa_praticada_MES_R$_duracao": "R$ 23.09 – R$ 81.60"
    },
    {
        "mes_nome": "Jan",
        "mes_num": 1,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": -0.01,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 26.52 – R$ 29.17",
        "n_obs_mes": 39,
        "r_quadrado_mes": 0.85,
        "faixa_praticada_MES_R$_duracao": "R$ 25.26 – R$ 26.52"
    },
    {
        "mes_nome": "Jan",
        "mes_num": 1,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": -0.32,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 94.92 – R$ 119.33",
        "n_obs_mes": 21,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 94.92 – R$ 108.48"
    },
    {
        "mes_nome": "Fev",
        "mes_num": 2,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": 0.0,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 47.60 – R$ 142.80",
        "n_obs_mes": 83,
        "r_quadrado_mes": 0.83,
        "faixa_praticada_MES_R$_duracao": "R$ 47.60 – R$ 142.80"
    },
    {
        "mes_nome": "Fev",
        "mes_num": 2,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": 0.39,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 83.25 – R$ 238.00",
        "n_obs_mes": 29,
        "r_quadrado_mes": 0.5,
        "faixa_praticada_MES_R$_duracao": "R$ 83.25 – R$ 238.00"
    },
    {
        "mes_nome": "Fev",
        "mes_num": 2,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.01,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 71.40 – R$ 121.10",
        "n_obs_mes": 82,
        "r_quadrado_mes": 0.82,
        "faixa_praticada_MES_R$_duracao": "R$ 25.97 – R$ 110.09"
    },
    {
        "mes_nome": "Fev",
        "mes_num": 2,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": -0.16,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 27.41 – R$ 114.55",
        "n_obs_mes": 39,
        "r_quadrado_mes": 0.45,
        "faixa_praticada_MES_R$_duracao": "R$ 25.37 – R$ 103.18"
    },
    {
        "mes_nome": "Fev",
        "mes_num": 2,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 1.4,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 110.16 – R$ 146.90",
        "n_obs_mes": 29,
        "r_quadrado_mes": 0.91,
        "faixa_praticada_MES_R$_duracao": "R$ 110.16 – R$ 146.90"
    },
    {
        "mes_nome": "Fev",
        "mes_num": 2,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": 0.2,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 64.74 – R$ 108.48",
        "n_obs_mes": 29,
        "r_quadrado_mes": 0.9,
        "faixa_praticada_MES_R$_duracao": "R$ 64.74 – R$ 108.48"
    },
    {
        "mes_nome": "Mar",
        "mes_num": 3,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": 0.14,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 8.80 – R$ 149.94",
        "n_obs_mes": 61,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 8.80 – R$ 149.94"
    },
    {
        "mes_nome": "Mar",
        "mes_num": 3,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.1,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 67.83 – R$ 101.06",
        "n_obs_mes": 62,
        "r_quadrado_mes": 0.93,
        "faixa_praticada_MES_R$_duracao": "R$ 25.97 – R$ 91.87"
    },
    {
        "mes_nome": "Mar",
        "mes_num": 3,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": 0.1,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 26.44 – R$ 114.38",
        "n_obs_mes": 21,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 26.44 – R$ 114.38"
    },
    {
        "mes_nome": "Mar",
        "mes_num": 3,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 1.19,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 113.00 – R$ 187.74",
        "n_obs_mes": 26,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 113.00 – R$ 187.74"
    },
    {
        "mes_nome": "Mar",
        "mes_num": 3,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": -0.0,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 62.30 – R$ 68.53",
        "n_obs_mes": 21,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 62.30 – R$ 62.30"
    },
    {
        "mes_nome": "Mar",
        "mes_num": 3,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": -0.09,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 132.17 – R$ 198.88",
        "n_obs_mes": 25,
        "r_quadrado_mes": 0.99,
        "faixa_praticada_MES_R$_duracao": "R$ 61.02 – R$ 180.80"
    },
    {
        "mes_nome": "Abr",
        "mes_num": 4,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": 0.01,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 8.80 – R$ 149.94",
        "n_obs_mes": 88,
        "r_quadrado_mes": 0.92,
        "faixa_praticada_MES_R$_duracao": "R$ 8.80 – R$ 149.94"
    },
    {
        "mes_nome": "Abr",
        "mes_num": 4,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": -0.21,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 303.45 – R$ 412.17",
        "n_obs_mes": 22,
        "r_quadrado_mes": 0.83,
        "faixa_praticada_MES_R$_duracao": "R$ 112.77 – R$ 374.70"
    },
    {
        "mes_nome": "Abr",
        "mes_num": 4,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": 0.26,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 25.97 – R$ 71.40",
        "n_obs_mes": 85,
        "r_quadrado_mes": 0.9,
        "faixa_praticada_MES_R$_duracao": "R$ 25.97 – R$ 71.40"
    },
    {
        "mes_nome": "Abr",
        "mes_num": 4,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": 0.43,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 26.65 – R$ 143.89",
        "n_obs_mes": 48,
        "r_quadrado_mes": 0.93,
        "faixa_praticada_MES_R$_duracao": "R$ 26.65 – R$ 143.89"
    },
    {
        "mes_nome": "Abr",
        "mes_num": 4,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 0.32,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 90.40 – R$ 176.22",
        "n_obs_mes": 25,
        "r_quadrado_mes": 0.95,
        "faixa_praticada_MES_R$_duracao": "R$ 90.40 – R$ 176.22"
    },
    {
        "mes_nome": "Abr",
        "mes_num": 4,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": 0.05,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 37.45 – R$ 68.44",
        "n_obs_mes": 38,
        "r_quadrado_mes": 0.67,
        "faixa_praticada_MES_R$_duracao": "R$ 37.45 – R$ 68.44"
    },
    {
        "mes_nome": "Abr",
        "mes_num": 4,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": 0.04,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 61.02 – R$ 110.24",
        "n_obs_mes": 30,
        "r_quadrado_mes": 0.98,
        "faixa_praticada_MES_R$_duracao": "R$ 61.02 – R$ 110.24"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": -0.31,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 96.33 – R$ 176.72",
        "n_obs_mes": 91,
        "r_quadrado_mes": 0.93,
        "faixa_praticada_MES_R$_duracao": "R$ 42.12 – R$ 160.66"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": -0.14,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 362.36 – R$ 445.06",
        "n_obs_mes": 25,
        "r_quadrado_mes": 0.86,
        "faixa_praticada_MES_R$_duracao": "R$ 108.49 – R$ 404.60"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.21,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 69.87 – R$ 125.64",
        "n_obs_mes": 81,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 25.97 – R$ 114.22"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Rotativo",
        "duracao_segundos": 45,
        "produto_chave_original": "comercial na faixa_45s",
        "beta_elasticidade": 0.52,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 133.87 – R$ 303.20",
        "n_obs_mes": 24,
        "r_quadrado_mes": 0.96,
        "faixa_praticada_MES_R$_duracao": "R$ 133.87 – R$ 303.20"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": 0.02,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 26.65 – R$ 245.90",
        "n_obs_mes": 56,
        "r_quadrado_mes": 0.93,
        "faixa_praticada_MES_R$_duracao": "R$ 26.65 – R$ 245.90"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 0.45,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 90.40 – R$ 192.10",
        "n_obs_mes": 27,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 90.40 – R$ 192.10"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": 0.0,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 72.19 – R$ 72.19",
        "n_obs_mes": 23,
        "r_quadrado_mes": 0.84,
        "faixa_praticada_MES_R$_duracao": "R$ 72.19 – R$ 72.19"
    },
    {
        "mes_nome": "Mai",
        "mes_num": 5,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": -0.59,
        "acao_recomendada": "Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 88.14 – R$ 88.14",
        "n_obs_mes": 27,
        "r_quadrado_mes": 0.96,
        "faixa_praticada_MES_R$_duracao": "R$ 67.80 – R$ 108.48"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": -0.02,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 89.25 – R$ 164.93",
        "n_obs_mes": 88,
        "r_quadrado_mes": 0.92,
        "faixa_praticada_MES_R$_duracao": "R$ 47.13 – R$ 149.94"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": -0.16,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 252.21 – R$ 455.53",
        "n_obs_mes": 28,
        "r_quadrado_mes": 0.84,
        "faixa_praticada_MES_R$_duracao": "R$ 108.36 – R$ 414.12"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": 0.18,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 22.77 – R$ 114.24",
        "n_obs_mes": 83,
        "r_quadrado_mes": 0.93,
        "faixa_praticada_MES_R$_duracao": "R$ 22.77 – R$ 114.24"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Rotativo",
        "duracao_segundos": 45,
        "produto_chave_original": "comercial na faixa_45s",
        "beta_elasticidade": -0.94,
        "acao_recomendada": "Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 82.00 – R$ 99.69",
        "n_obs_mes": 31,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 81.95 – R$ 312.38"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": -2.42,
        "acao_recomendada": "Reduzir ++ (Alt. Elástico)",
        "faixa_sugerida_R$_duracao": "R$ 23.98 – R$ 26.65",
        "n_obs_mes": 49,
        "r_quadrado_mes": 0.95,
        "faixa_praticada_MES_R$_duracao": "R$ 26.65 – R$ 145.23"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": -0.19,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 137.86 – R$ 208.62",
        "n_obs_mes": 25,
        "r_quadrado_mes": 0.96,
        "faixa_praticada_MES_R$_duracao": "R$ 90.40 – R$ 189.66"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": 0.0,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 79.82 – R$ 79.82",
        "n_obs_mes": 20,
        "r_quadrado_mes": 0.91,
        "faixa_praticada_MES_R$_duracao": "R$ 79.82 – R$ 79.82"
    },
    {
        "mes_nome": "Jun",
        "mes_num": 6,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": 0.14,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 67.57 – R$ 108.48",
        "n_obs_mes": 27,
        "r_quadrado_mes": 0.99,
        "faixa_praticada_MES_R$_duracao": "R$ 67.57 – R$ 108.48"
    },
    {
        "mes_nome": "Jul",
        "mes_num": 7,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": 0.06,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 37.80 – R$ 149.56",
        "n_obs_mes": 92,
        "r_quadrado_mes": 0.92,
        "faixa_praticada_MES_R$_duracao": "R$ 37.80 – R$ 149.56"
    },
    {
        "mes_nome": "Jul",
        "mes_num": 7,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": 0.18,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 179.58 – R$ 414.12",
        "n_obs_mes": 40,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 179.58 – R$ 414.12"
    },
    {
        "mes_nome": "Jul",
        "mes_num": 7,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.11,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 70.69 – R$ 157.08",
        "n_obs_mes": 93,
        "r_quadrado_mes": 0.92,
        "faixa_praticada_MES_R$_duracao": "R$ 33.19 – R$ 142.80"
    },
    {
        "mes_nome": "Jul",
        "mes_num": 7,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": 0.4,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 26.65 – R$ 159.88",
        "n_obs_mes": 45,
        "r_quadrado_mes": 0.96,
        "faixa_praticada_MES_R$_duracao": "R$ 26.65 – R$ 159.88"
    },
    {
        "mes_nome": "Jul",
        "mes_num": 7,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 0.25,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 29.29 – R$ 180.80",
        "n_obs_mes": 29,
        "r_quadrado_mes": 0.99,
        "faixa_praticada_MES_R$_duracao": "R$ 29.29 – R$ 180.80"
    },
    {
        "mes_nome": "Jul",
        "mes_num": 7,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": 1.81,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 69.60 – R$ 79.54",
        "n_obs_mes": 23,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 69.60 – R$ 79.54"
    },
    {
        "mes_nome": "Jul",
        "mes_num": 7,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": 0.64,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 88.14 – R$ 103.76",
        "n_obs_mes": 23,
        "r_quadrado_mes": 0.93,
        "faixa_praticada_MES_R$_duracao": "R$ 88.14 – R$ 103.76"
    },
    {
        "mes_nome": "Ago",
        "mes_num": 8,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": 0.28,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 46.70 – R$ 160.65",
        "n_obs_mes": 88,
        "r_quadrado_mes": 0.92,
        "faixa_praticada_MES_R$_duracao": "R$ 46.70 – R$ 160.65"
    },
    {
        "mes_nome": "Ago",
        "mes_num": 8,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": -0.1,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 303.45 – R$ 445.06",
        "n_obs_mes": 34,
        "r_quadrado_mes": 0.8,
        "faixa_praticada_MES_R$_duracao": "R$ 64.38 – R$ 404.60"
    },
    {
        "mes_nome": "Ago",
        "mes_num": 8,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": 0.12,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 25.97 – R$ 120.67",
        "n_obs_mes": 90,
        "r_quadrado_mes": 0.89,
        "faixa_praticada_MES_R$_duracao": "R$ 25.97 – R$ 120.67"
    },
    {
        "mes_nome": "Ago",
        "mes_num": 8,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": 0.32,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 32.55 – R$ 119.92",
        "n_obs_mes": 39,
        "r_quadrado_mes": 0.82,
        "faixa_praticada_MES_R$_duracao": "R$ 32.55 – R$ 119.92"
    },
    {
        "mes_nome": "Ago",
        "mes_num": 8,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 0.51,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 110.16 – R$ 158.20",
        "n_obs_mes": 37,
        "r_quadrado_mes": 0.86,
        "faixa_praticada_MES_R$_duracao": "R$ 110.16 – R$ 158.20"
    },
    {
        "mes_nome": "Ago",
        "mes_num": 8,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": -2.68,
        "acao_recomendada": "Reduzir ++ (Alt. Elástico)",
        "faixa_sugerida_R$_duracao": "R$ 56.25 – R$ 62.50",
        "n_obs_mes": 43,
        "r_quadrado_mes": 0.85,
        "faixa_praticada_MES_R$_duracao": "R$ 62.50 – R$ 100.00"
    },
    {
        "mes_nome": "Ago",
        "mes_num": 8,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": 0.2,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 88.14 – R$ 108.72",
        "n_obs_mes": 23,
        "r_quadrado_mes": 0.93,
        "faixa_praticada_MES_R$_duracao": "R$ 88.14 – R$ 108.72"
    },
    {
        "mes_nome": "Set",
        "mes_num": 9,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": 0.25,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 47.60 – R$ 151.72",
        "n_obs_mes": 88,
        "r_quadrado_mes": 0.95,
        "faixa_praticada_MES_R$_duracao": "R$ 47.60 – R$ 151.72"
    },
    {
        "mes_nome": "Set",
        "mes_num": 9,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.11,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 80.32 – R$ 157.08",
        "n_obs_mes": 84,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 23.09 – R$ 142.80"
    },
    {
        "mes_nome": "Set",
        "mes_num": 9,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": -0.37,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 43.38 – R$ 140.04",
        "n_obs_mes": 49,
        "r_quadrado_mes": 0.91,
        "faixa_praticada_MES_R$_duracao": "R$ 28.28 – R$ 127.31"
    },
    {
        "mes_nome": "Set",
        "mes_num": 9,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 0.41,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 110.16 – R$ 180.80",
        "n_obs_mes": 38,
        "r_quadrado_mes": 0.99,
        "faixa_praticada_MES_R$_duracao": "R$ 110.16 – R$ 180.80"
    },
    {
        "mes_nome": "Set",
        "mes_num": 9,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": 0.15,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 63.43 – R$ 100.00",
        "n_obs_mes": 42,
        "r_quadrado_mes": 0.86,
        "faixa_praticada_MES_R$_duracao": "R$ 63.43 – R$ 100.00"
    },
    {
        "mes_nome": "Set",
        "mes_num": 9,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": -0.37,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 88.14 – R$ 161.11",
        "n_obs_mes": 24,
        "r_quadrado_mes": 1.0,
        "faixa_praticada_MES_R$_duracao": "R$ 80.79 – R$ 146.46"
    },
    {
        "mes_nome": "Out",
        "mes_num": 10,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": -0.08,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 127.98 – R$ 211.35",
        "n_obs_mes": 62,
        "r_quadrado_mes": 0.96,
        "faixa_praticada_MES_R$_duracao": "R$ 25.85 – R$ 192.13"
    },
    {
        "mes_nome": "Out",
        "mes_num": 10,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.17,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 72.96 – R$ 157.08",
        "n_obs_mes": 62,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 23.09 – R$ 142.80"
    },
    {
        "mes_nome": "Out",
        "mes_num": 10,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": -0.07,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 90.10 – R$ 117.80",
        "n_obs_mes": 49,
        "r_quadrado_mes": 0.96,
        "faixa_praticada_MES_R$_duracao": "R$ 24.51 – R$ 107.09"
    },
    {
        "mes_nome": "Out",
        "mes_num": 10,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 0.39,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 39.58 – R$ 226.00",
        "n_obs_mes": 28,
        "r_quadrado_mes": 0.96,
        "faixa_praticada_MES_R$_duracao": "R$ 39.58 – R$ 226.00"
    },
    {
        "mes_nome": "Out",
        "mes_num": 10,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": 0.0,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 61.30 – R$ 115.10",
        "n_obs_mes": 23,
        "r_quadrado_mes": 0.9,
        "faixa_praticada_MES_R$_duracao": "R$ 61.30 – R$ 115.10"
    },
    {
        "mes_nome": "Out",
        "mes_num": 10,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": 0.0,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 88.14 – R$ 88.14",
        "n_obs_mes": 23,
        "r_quadrado_mes": 0.9,
        "faixa_praticada_MES_R$_duracao": "R$ 88.14 – R$ 88.14"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": -0.24,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 128.84 – R$ 157.08",
        "n_obs_mes": 83,
        "r_quadrado_mes": 0.91,
        "faixa_praticada_MES_R$_duracao": "R$ 38.23 – R$ 142.80"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": 0.14,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 95.53 – R$ 538.36",
        "n_obs_mes": 42,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 95.53 – R$ 538.36"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.02,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 87.47 – R$ 157.08",
        "n_obs_mes": 85,
        "r_quadrado_mes": 0.92,
        "faixa_praticada_MES_R$_duracao": "R$ 19.93 – R$ 142.80"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Rotativo",
        "duracao_segundos": 45,
        "produto_chave_original": "comercial na faixa_45s",
        "beta_elasticidade": 0.04,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 36.83 – R$ 133.28",
        "n_obs_mes": 35,
        "r_quadrado_mes": 0.94,
        "faixa_praticada_MES_R$_duracao": "R$ 36.83 – R$ 133.28"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": 0.05,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 25.25 – R$ 115.16",
        "n_obs_mes": 59,
        "r_quadrado_mes": 0.88,
        "faixa_praticada_MES_R$_duracao": "R$ 25.25 – R$ 115.16"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 0.11,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 90.40 – R$ 157.83",
        "n_obs_mes": 24,
        "r_quadrado_mes": 0.99,
        "faixa_praticada_MES_R$_duracao": "R$ 90.40 – R$ 157.83"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": -0.16,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 63.43 – R$ 80.94",
        "n_obs_mes": 36,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 51.92 – R$ 73.58"
    },
    {
        "mes_nome": "Nov",
        "mes_num": 11,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": -1.03,
        "acao_recomendada": "Reduzir (Elástico)",
        "faixa_sugerida_R$_duracao": "R$ 87.61 – R$ 88.14",
        "n_obs_mes": 25,
        "r_quadrado_mes": 0.97,
        "faixa_praticada_MES_R$_duracao": "R$ 67.80 – R$ 125.60"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Rotativo",
        "duracao_segundos": 30,
        "produto_chave_original": "comercial na faixa_30s",
        "beta_elasticidade": 0.2,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 57.72 – R$ 172.56",
        "n_obs_mes": 90,
        "r_quadrado_mes": 0.9,
        "faixa_praticada_MES_R$_duracao": "R$ 57.72 – R$ 172.56"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Rotativo",
        "duracao_segundos": 60,
        "produto_chave_original": "comercial na faixa_60s",
        "beta_elasticidade": -0.13,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 281.49 – R$ 592.19",
        "n_obs_mes": 27,
        "r_quadrado_mes": 0.99,
        "faixa_praticada_MES_R$_duracao": "R$ 55.25 – R$ 538.36"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Rotativo",
        "duracao_segundos": 15,
        "produto_chave_original": "comercial na faixa_15s",
        "beta_elasticidade": -0.02,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 81.75 – R$ 157.08",
        "n_obs_mes": 92,
        "r_quadrado_mes": 0.91,
        "faixa_praticada_MES_R$_duracao": "R$ 25.97 – R$ 142.80"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Rotativo",
        "duracao_segundos": 45,
        "produto_chave_original": "comercial na faixa_45s",
        "beta_elasticidade": -0.03,
        "acao_recomendada": "Aumentar ++ (Alt. Inelástico)",
        "faixa_sugerida_R$_duracao": "R$ 109.97 – R$ 394.05",
        "n_obs_mes": 27,
        "r_quadrado_mes": 0.99,
        "faixa_praticada_MES_R$_duracao": "R$ 25.66 – R$ 357.00"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Determinado",
        "duracao_segundos": 30,
        "produto_chave_original": "spot determinado_30s",
        "beta_elasticidade": 0.16,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 25.39 – R$ 165.25",
        "n_obs_mes": 56,
        "r_quadrado_mes": 0.77,
        "faixa_praticada_MES_R$_duracao": "R$ 25.39 – R$ 165.25"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 30,
        "produto_chave_original": "rotativo 07-19h_30s",
        "beta_elasticidade": 4.14,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 124.30 – R$ 141.96",
        "n_obs_mes": 29,
        "r_quadrado_mes": 0.95,
        "faixa_praticada_MES_R$_duracao": "R$ 124.30 – R$ 141.96"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Determinado",
        "duracao_segundos": 15,
        "produto_chave_original": "spot determinado_15s",
        "beta_elasticidade": 0.3,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 51.99 – R$ 73.67",
        "n_obs_mes": 33,
        "r_quadrado_mes": 0.91,
        "faixa_praticada_MES_R$_duracao": "R$ 51.99 – R$ 73.67"
    },
    {
        "mes_nome": "Dez",
        "mes_num": 12,
        "nome_formato": "Rotativo (07-19)",
        "duracao_segundos": 15,
        "produto_chave_original": "rotativo 07-19h_15s",
        "beta_elasticidade": 0.0,
        "acao_recomendada": "Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao": "R$ 88.14 – R$ 88.14",
        "n_obs_mes": 26,
        "r_quadrado_mes": 0.95,
        "faixa_praticada_MES_R$_duracao": "R$ 88.14 – R$ 88.14"
    }
]