export const RAW_DATA = [
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":-0.03,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 28.39 – R$ 193.48",
        "n_obs_mes":40,
        "r_quadrado_mes":0.71,
        "faixa_praticada_MES_R$_duracao":"R$ 25.26 – R$ 164.33"
    },
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":0.37,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 25.31 – R$ 116.11",
        "n_obs_mes":87,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 23.65 – R$ 108.48"
    },
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":-0.14,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 105.09 – R$ 167.33",
        "n_obs_mes":93,
        "r_quadrado_mes":0.9,
        "faixa_praticada_MES_R$_duracao":"R$ 55.50 – R$ 142.12"
    },
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":-0.04,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 281.18 – R$ 438.30",
        "n_obs_mes":49,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 36.96 – R$ 372.26"
    },
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":0.03,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 117.71 – R$ 837.20",
        "n_obs_mes":25,
        "r_quadrado_mes":0.87,
        "faixa_praticada_MES_R$_duracao":"R$ 109.97 – R$ 782.16"
    },
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":-0.64,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 65.06 – R$ 76.83",
        "n_obs_mes":29,
        "r_quadrado_mes":0.97,
        "faixa_praticada_MES_R$_duracao":"R$ 34.47 – R$ 102.54"
    },
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":0.27,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 91.46 – R$ 132.47",
        "n_obs_mes":23,
        "r_quadrado_mes":0.94,
        "faixa_praticada_MES_R$_duracao":"R$ 85.45 – R$ 123.76"
    },
    {
        "mes_nome":"Jan",
        "mes_num":1,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":0.55,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 101.60 – R$ 116.11",
        "n_obs_mes":21,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 94.92 – R$ 108.48"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":-0.13,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 29.34 – R$ 121.49",
        "n_obs_mes":39,
        "r_quadrado_mes":0.42,
        "faixa_praticada_MES_R$_duracao":"R$ 25.37 – R$ 103.18"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 85.14 – R$ 85.14",
        "n_obs_mes":19,
        "r_quadrado_mes":0.51,
        "faixa_praticada_MES_R$_duracao":"R$ 79.54 – R$ 79.54"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":0.1,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 27.80 – R$ 117.84",
        "n_obs_mes":85,
        "r_quadrado_mes":0.83,
        "faixa_praticada_MES_R$_duracao":"R$ 25.97 – R$ 110.09"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":0.39,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 50.95 – R$ 133.74",
        "n_obs_mes":85,
        "r_quadrado_mes":0.83,
        "faixa_praticada_MES_R$_duracao":"R$ 47.60 – R$ 124.95"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":0.2,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 89.11 – R$ 254.75",
        "n_obs_mes":33,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 83.25 – R$ 238.00"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":0.15,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 58.85 – R$ 205.79",
        "n_obs_mes":16,
        "r_quadrado_mes":0.86,
        "faixa_praticada_MES_R$_duracao":"R$ 54.98 – R$ 192.26"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":-1.09,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 60.37 – R$ 76.79",
        "n_obs_mes":29,
        "r_quadrado_mes":0.87,
        "faixa_praticada_MES_R$_duracao":"R$ 46.86 – R$ 79.05"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":-0.27,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 118.90 – R$ 155.67",
        "n_obs_mes":29,
        "r_quadrado_mes":0.84,
        "faixa_praticada_MES_R$_duracao":"R$ 85.45 – R$ 132.21"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":1.01,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 117.91 – R$ 157.24",
        "n_obs_mes":29,
        "r_quadrado_mes":0.85,
        "faixa_praticada_MES_R$_duracao":"R$ 110.16 – R$ 146.90"
    },
    {
        "mes_nome":"Fev",
        "mes_num":2,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":0.6,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 69.30 – R$ 116.11",
        "n_obs_mes":29,
        "r_quadrado_mes":0.87,
        "faixa_praticada_MES_R$_duracao":"R$ 64.74 – R$ 108.48"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":-0.12,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 75.36 – R$ 134.67",
        "n_obs_mes":21,
        "r_quadrado_mes":0.85,
        "faixa_praticada_MES_R$_duracao":"R$ 26.44 – R$ 114.38"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 66.68 – R$ 66.68",
        "n_obs_mes":21,
        "r_quadrado_mes":0.79,
        "faixa_praticada_MES_R$_duracao":"R$ 62.30 – R$ 62.30"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":0.09,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 27.80 – R$ 91.71",
        "n_obs_mes":62,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 25.97 – R$ 85.68"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":0.14,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 49.29 – R$ 160.49",
        "n_obs_mes":62,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 46.05 – R$ 149.94"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":-0.5,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 65.83 – R$ 76.83",
        "n_obs_mes":31,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 51.27 – R$ 82.03"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":-0.94,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 112.95 – R$ 122.86",
        "n_obs_mes":31,
        "r_quadrado_mes":0.96,
        "faixa_praticada_MES_R$_duracao":"R$ 102.54 – R$ 170.90"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Rotativo",
        "duracao_segundos":45,
        "produto_chave_original":"rotativo_45s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 274.39 – R$ 274.39",
        "n_obs_mes":15,
        "r_quadrado_mes":0.98,
        "faixa_praticada_MES_R$_duracao":"R$ 256.35 – R$ 256.35"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.08,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 120.95 – R$ 200.95",
        "n_obs_mes":26,
        "r_quadrado_mes":0.94,
        "faixa_praticada_MES_R$_duracao":"R$ 113.00 – R$ 187.74"
    },
    {
        "mes_nome":"Mar",
        "mes_num":3,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":-0.15,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 141.47 – R$ 212.88",
        "n_obs_mes":25,
        "r_quadrado_mes":0.97,
        "faixa_praticada_MES_R$_duracao":"R$ 61.02 – R$ 180.80"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":-0.66,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 95.03 – R$ 111.13",
        "n_obs_mes":48,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 26.65 – R$ 143.89"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":-0.03,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 73.26 – R$ 80.59",
        "n_obs_mes":38,
        "r_quadrado_mes":0.53,
        "faixa_praticada_MES_R$_duracao":"R$ 37.45 – R$ 68.44"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":0.41,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 27.80 – R$ 76.42",
        "n_obs_mes":86,
        "r_quadrado_mes":0.9,
        "faixa_praticada_MES_R$_duracao":"R$ 25.97 – R$ 71.40"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":0.29,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 47.52 – R$ 143.30",
        "n_obs_mes":90,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 44.40 – R$ 133.88"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":-0.08,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 324.81 – R$ 441.18",
        "n_obs_mes":22,
        "r_quadrado_mes":0.81,
        "faixa_praticada_MES_R$_duracao":"R$ 112.77 – R$ 374.70"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":-0.46,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 177.68 – R$ 211.28",
        "n_obs_mes":28,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 38.96 – R$ 179.44"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":-0.5,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 76.14 – R$ 104.06",
        "n_obs_mes":30,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 51.27 – R$ 88.38"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":-0.59,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 91.46 – R$ 119.08",
        "n_obs_mes":30,
        "r_quadrado_mes":0.96,
        "faixa_praticada_MES_R$_duracao":"R$ 78.96 – R$ 128.18"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.71,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 96.76 – R$ 188.62",
        "n_obs_mes":25,
        "r_quadrado_mes":0.9,
        "faixa_praticada_MES_R$_duracao":"R$ 90.40 – R$ 176.22"
    },
    {
        "mes_nome":"Abr",
        "mes_num":4,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":0.45,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 65.31 – R$ 118.00",
        "n_obs_mes":30,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 61.02 – R$ 110.24"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":0.09,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 28.53 – R$ 263.21",
        "n_obs_mes":56,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 26.65 – R$ 245.90"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 77.27 – R$ 77.27",
        "n_obs_mes":23,
        "r_quadrado_mes":0.3,
        "faixa_praticada_MES_R$_duracao":"R$ 72.19 – R$ 72.19"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":-0.25,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 65.85 – R$ 134.49",
        "n_obs_mes":92,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 25.97 – R$ 114.22"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":-0.54,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 91.46 – R$ 96.08",
        "n_obs_mes":93,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 31.68 – R$ 140.41"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":-0.11,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 387.86 – R$ 441.18",
        "n_obs_mes":27,
        "r_quadrado_mes":0.83,
        "faixa_praticada_MES_R$_duracao":"R$ 108.49 – R$ 374.70"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":0.1,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 106.61 – R$ 324.54",
        "n_obs_mes":28,
        "r_quadrado_mes":0.93,
        "faixa_praticada_MES_R$_duracao":"R$ 99.60 – R$ 303.20"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":0.47,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 45.43 – R$ 124.47",
        "n_obs_mes":31,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 42.44 – R$ 116.29"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":-1.08,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 106.97 – R$ 109.76",
        "n_obs_mes":31,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 82.78 – R$ 119.63"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":-0.34,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 106.99 – R$ 226.18",
        "n_obs_mes":27,
        "r_quadrado_mes":0.88,
        "faixa_praticada_MES_R$_duracao":"R$ 90.40 – R$ 192.10"
    },
    {
        "mes_nome":"Mai",
        "mes_num":5,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":-0.89,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 94.34",
        "n_obs_mes":27,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 67.80 – R$ 108.48"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":-2.45,
        "acao_recomendada":"Reduzir ++ (Elástico)",
        "faixa_sugerida_R$_duracao":"R$ 25.67 – R$ 28.53",
        "n_obs_mes":49,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 26.65 – R$ 145.23"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 85.44 – R$ 85.44",
        "n_obs_mes":20,
        "r_quadrado_mes":0.74,
        "faixa_praticada_MES_R$_duracao":"R$ 79.82 – R$ 79.82"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":0.07,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 24.38 – R$ 122.28",
        "n_obs_mes":87,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 22.77 – R$ 114.24"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":0.05,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 45.80 – R$ 133.74",
        "n_obs_mes":90,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 42.79 – R$ 124.95"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":-0.22,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 387.86 – R$ 531.26",
        "n_obs_mes":30,
        "r_quadrado_mes":0.69,
        "faixa_praticada_MES_R$_duracao":"R$ 108.36 – R$ 451.21"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":-0.18,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 106.71 – R$ 367.80",
        "n_obs_mes":40,
        "r_quadrado_mes":0.93,
        "faixa_praticada_MES_R$_duracao":"R$ 81.95 – R$ 312.38"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":-0.07,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 76.49 – R$ 95.58",
        "n_obs_mes":30,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 45.43 – R$ 81.18"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":2.75,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 100.61 – R$ 127.62",
        "n_obs_mes":30,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 94.00 – R$ 119.23"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.3,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 96.76 – R$ 203.00",
        "n_obs_mes":25,
        "r_quadrado_mes":0.87,
        "faixa_praticada_MES_R$_duracao":"R$ 90.40 – R$ 189.66"
    },
    {
        "mes_nome":"Jun",
        "mes_num":6,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":-1.31,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 94.34",
        "n_obs_mes":27,
        "r_quadrado_mes":0.96,
        "faixa_praticada_MES_R$_duracao":"R$ 67.57 – R$ 108.48"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":0.17,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 28.53 – R$ 171.13",
        "n_obs_mes":45,
        "r_quadrado_mes":0.88,
        "faixa_praticada_MES_R$_duracao":"R$ 26.65 – R$ 159.88"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.55,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 74.50 – R$ 85.14",
        "n_obs_mes":23,
        "r_quadrado_mes":0.66,
        "faixa_praticada_MES_R$_duracao":"R$ 69.60 – R$ 79.54"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":0.14,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 35.32 – R$ 109.76",
        "n_obs_mes":93,
        "r_quadrado_mes":0.9,
        "faixa_praticada_MES_R$_duracao":"R$ 33.00 – R$ 102.54"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":-0.19,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 107.04 – R$ 176.09",
        "n_obs_mes":93,
        "r_quadrado_mes":0.9,
        "faixa_praticada_MES_R$_duracao":"R$ 37.80 – R$ 149.56"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":-0.28,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 378.94 – R$ 487.59",
        "n_obs_mes":51,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 179.58 – R$ 414.12"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":-0.74,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 211.37 – R$ 268.29",
        "n_obs_mes":16,
        "r_quadrado_mes":0.97,
        "faixa_praticada_MES_R$_duracao":"R$ 144.30 – R$ 250.65"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":-0.13,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 87.81 – R$ 103.78",
        "n_obs_mes":25,
        "r_quadrado_mes":0.83,
        "faixa_praticada_MES_R$_duracao":"R$ 51.27 – R$ 88.14"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":1.2,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 91.46 – R$ 118.58",
        "n_obs_mes":31,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 85.45 – R$ 110.78"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.33,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 31.35 – R$ 193.52",
        "n_obs_mes":29,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 29.29 – R$ 180.80"
    },
    {
        "mes_nome":"Jul",
        "mes_num":7,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":1.15,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 111.07",
        "n_obs_mes":23,
        "r_quadrado_mes":0.75,
        "faixa_praticada_MES_R$_duracao":"R$ 88.14 – R$ 103.76"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":-1.36,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 117.66 – R$ 117.66",
        "n_obs_mes":39,
        "r_quadrado_mes":0.7,
        "faixa_praticada_MES_R$_duracao":"R$ 32.55 – R$ 119.92"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":-3.45,
        "acao_recomendada":"Reduzir ++ (Elástico)",
        "faixa_sugerida_R$_duracao":"R$ 60.21 – R$ 66.90",
        "n_obs_mes":43,
        "r_quadrado_mes":0.73,
        "faixa_praticada_MES_R$_duracao":"R$ 62.50 – R$ 100.00"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":0.11,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 27.80 – R$ 129.16",
        "n_obs_mes":92,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 25.97 – R$ 120.67"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":0.32,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 61.78 – R$ 171.96",
        "n_obs_mes":91,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 57.72 – R$ 160.65"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":0.1,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 68.91 – R$ 433.07",
        "n_obs_mes":35,
        "r_quadrado_mes":0.75,
        "faixa_praticada_MES_R$_duracao":"R$ 64.38 – R$ 404.60"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":-0.14,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 164.63 – R$ 210.17",
        "n_obs_mes":16,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 72.15 – R$ 178.50"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":0.1,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 65.85 – R$ 87.81",
        "n_obs_mes":25,
        "r_quadrado_mes":0.8,
        "faixa_praticada_MES_R$_duracao":"R$ 61.52 – R$ 82.03"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":-0.09,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 127.86 – R$ 201.22",
        "n_obs_mes":31,
        "r_quadrado_mes":0.9,
        "faixa_praticada_MES_R$_duracao":"R$ 70.41 – R$ 170.90"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.79,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 117.91 – R$ 169.33",
        "n_obs_mes":37,
        "r_quadrado_mes":0.8,
        "faixa_praticada_MES_R$_duracao":"R$ 110.16 – R$ 158.20"
    },
    {
        "mes_nome":"Ago",
        "mes_num":8,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":1.95,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 116.37",
        "n_obs_mes":23,
        "r_quadrado_mes":0.67,
        "faixa_praticada_MES_R$_duracao":"R$ 88.14 – R$ 108.72"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":-0.47,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 46.44 – R$ 149.90",
        "n_obs_mes":49,
        "r_quadrado_mes":0.87,
        "faixa_praticada_MES_R$_duracao":"R$ 28.28 – R$ 127.31"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.16,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 67.89 – R$ 107.04",
        "n_obs_mes":42,
        "r_quadrado_mes":0.76,
        "faixa_praticada_MES_R$_duracao":"R$ 63.43 – R$ 100.00"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":-0.13,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 85.98 – R$ 168.13",
        "n_obs_mes":88,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 23.09 – R$ 142.80"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":-0.18,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 127.37 – R$ 178.64",
        "n_obs_mes":90,
        "r_quadrado_mes":0.93,
        "faixa_praticada_MES_R$_duracao":"R$ 47.60 – R$ 151.72"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":0.12,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 64.51 – R$ 576.24",
        "n_obs_mes":16,
        "r_quadrado_mes":0.94,
        "faixa_praticada_MES_R$_duracao":"R$ 60.27 – R$ 538.36"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":3.64,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 134.15 – R$ 194.31",
        "n_obs_mes":15,
        "r_quadrado_mes":0.97,
        "faixa_praticada_MES_R$_duracao":"R$ 125.33 – R$ 181.53"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":-0.01,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 65.85 – R$ 79.99",
        "n_obs_mes":23,
        "r_quadrado_mes":0.94,
        "faixa_praticada_MES_R$_duracao":"R$ 43.13 – R$ 67.94"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":0.63,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 100.61 – R$ 137.20",
        "n_obs_mes":30,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 94.00 – R$ 128.17"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.02,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 117.91 – R$ 193.52",
        "n_obs_mes":38,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 110.16 – R$ 180.80"
    },
    {
        "mes_nome":"Set",
        "mes_num":9,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":-0.71,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 94.34",
        "n_obs_mes":24,
        "r_quadrado_mes":0.88,
        "faixa_praticada_MES_R$_duracao":"R$ 80.79 – R$ 146.46"
    },
    {
        "mes_nome":"Out",
        "mes_num":10,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":0.01,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 26.23 – R$ 114.63",
        "n_obs_mes":49,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 24.51 – R$ 107.09"
    },
    {
        "mes_nome":"Out",
        "mes_num":10,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 65.61 – R$ 123.20",
        "n_obs_mes":23,
        "r_quadrado_mes":0.77,
        "faixa_praticada_MES_R$_duracao":"R$ 61.30 – R$ 115.10"
    },
    {
        "mes_nome":"Out",
        "mes_num":10,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":-0.16,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 77.38 – R$ 168.13",
        "n_obs_mes":62,
        "r_quadrado_mes":0.96,
        "faixa_praticada_MES_R$_duracao":"R$ 25.97 – R$ 142.80"
    },
    {
        "mes_nome":"Out",
        "mes_num":10,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":-0.07,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 136.51 – R$ 213.72",
        "n_obs_mes":62,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 25.85 – R$ 181.52"
    },
    {
        "mes_nome":"Out",
        "mes_num":10,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":1.14,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 98.78 – R$ 128.05",
        "n_obs_mes":31,
        "r_quadrado_mes":0.97,
        "faixa_praticada_MES_R$_duracao":"R$ 92.29 – R$ 119.63"
    },
    {
        "mes_nome":"Out",
        "mes_num":10,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.62,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 42.37 – R$ 241.91",
        "n_obs_mes":28,
        "r_quadrado_mes":0.95,
        "faixa_praticada_MES_R$_duracao":"R$ 39.58 – R$ 226.00"
    },
    {
        "mes_nome":"Out",
        "mes_num":10,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 94.34",
        "n_obs_mes":23,
        "r_quadrado_mes":0.77,
        "faixa_praticada_MES_R$_duracao":"R$ 88.14 – R$ 88.14"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":0.01,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 27.03 – R$ 123.26",
        "n_obs_mes":59,
        "r_quadrado_mes":0.87,
        "faixa_praticada_MES_R$_duracao":"R$ 25.25 – R$ 115.16"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":-0.68,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 67.89 – R$ 67.89",
        "n_obs_mes":36,
        "r_quadrado_mes":0.94,
        "faixa_praticada_MES_R$_duracao":"R$ 51.92 – R$ 73.58"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":-0.05,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 95.03 – R$ 168.13",
        "n_obs_mes":89,
        "r_quadrado_mes":0.92,
        "faixa_praticada_MES_R$_duracao":"R$ 19.93 – R$ 142.80"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":0.39,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 55.25 – R$ 152.85",
        "n_obs_mes":86,
        "r_quadrado_mes":0.91,
        "faixa_praticada_MES_R$_duracao":"R$ 51.62 – R$ 142.80"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":0.25,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 102.25 – R$ 576.24",
        "n_obs_mes":59,
        "r_quadrado_mes":0.96,
        "faixa_praticada_MES_R$_duracao":"R$ 95.53 – R$ 538.36"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":0.06,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 39.42 – R$ 211.29",
        "n_obs_mes":36,
        "r_quadrado_mes":0.94,
        "faixa_praticada_MES_R$_duracao":"R$ 36.83 – R$ 197.40"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":0.04,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 22.96 – R$ 109.76",
        "n_obs_mes":27,
        "r_quadrado_mes":0.93,
        "faixa_praticada_MES_R$_duracao":"R$ 21.45 – R$ 102.54"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":-0.74,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 118.90 – R$ 126.91",
        "n_obs_mes":30,
        "r_quadrado_mes":0.93,
        "faixa_praticada_MES_R$_duracao":"R$ 102.54 – R$ 119.63"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":0.19,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 96.76 – R$ 168.94",
        "n_obs_mes":24,
        "r_quadrado_mes":0.97,
        "faixa_praticada_MES_R$_duracao":"R$ 90.40 – R$ 157.83"
    },
    {
        "mes_nome":"Nov",
        "mes_num":11,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":-0.93,
        "acao_recomendada":"Aumentar (Inelástico)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 94.34",
        "n_obs_mes":25,
        "r_quadrado_mes":0.97,
        "faixa_praticada_MES_R$_duracao":"R$ 67.80 – R$ 125.60"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Determinado",
        "duracao_segundos":30,
        "produto_chave_original":"spot determinado_30s",
        "beta_elasticidade":0.35,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 27.18 – R$ 176.88",
        "n_obs_mes":56,
        "r_quadrado_mes":0.58,
        "faixa_praticada_MES_R$_duracao":"R$ 25.39 – R$ 165.25"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Determinado",
        "duracao_segundos":15,
        "produto_chave_original":"spot determinado_15s",
        "beta_elasticidade":0.31,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 55.64 – R$ 78.86",
        "n_obs_mes":33,
        "r_quadrado_mes":0.86,
        "faixa_praticada_MES_R$_duracao":"R$ 51.99 – R$ 73.67"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Faixa",
        "duracao_segundos":15,
        "produto_chave_original":"comercial na faixa_15s",
        "beta_elasticidade":-0.01,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 76.83 – R$ 168.13",
        "n_obs_mes":92,
        "r_quadrado_mes":0.89,
        "faixa_praticada_MES_R$_duracao":"R$ 25.97 – R$ 142.80"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Faixa",
        "duracao_segundos":30,
        "produto_chave_original":"comercial na faixa_30s",
        "beta_elasticidade":0.09,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 70.43 – R$ 184.71",
        "n_obs_mes":92,
        "r_quadrado_mes":0.88,
        "faixa_praticada_MES_R$_duracao":"R$ 65.80 – R$ 172.56"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Faixa",
        "duracao_segundos":60,
        "produto_chave_original":"comercial na faixa_60s",
        "beta_elasticidade":-0.07,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 294.84 – R$ 633.87",
        "n_obs_mes":44,
        "r_quadrado_mes":0.94,
        "faixa_praticada_MES_R$_duracao":"R$ 55.25 – R$ 538.36"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Faixa",
        "duracao_segundos":45,
        "produto_chave_original":"comercial na faixa_45s",
        "beta_elasticidade":-0.01,
        "acao_recomendada":"Aumentar ++ (Super Inel.)",
        "faixa_sugerida_R$_duracao":"R$ 105.65 – R$ 420.34",
        "n_obs_mes":37,
        "r_quadrado_mes":0.96,
        "faixa_praticada_MES_R$_duracao":"R$ 25.66 – R$ 357.00"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Rotativo",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo_15s",
        "beta_elasticidade":0.88,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 49.39 – R$ 82.32",
        "n_obs_mes":28,
        "r_quadrado_mes":0.9,
        "faixa_praticada_MES_R$_duracao":"R$ 46.14 – R$ 76.91"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Rotativo",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo_30s",
        "beta_elasticidade":2.84,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 109.47 – R$ 122.53",
        "n_obs_mes":31,
        "r_quadrado_mes":0.88,
        "faixa_praticada_MES_R$_duracao":"R$ 102.27 – R$ 114.47"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Rotativo",
        "duracao_segundos":60,
        "produto_chave_original":"rotativo_60s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 256.10 – R$ 256.10",
        "n_obs_mes":20,
        "r_quadrado_mes":0.44,
        "faixa_praticada_MES_R$_duracao":"R$ 239.26 – R$ 239.26"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":30,
        "produto_chave_original":"rotativo 07-19h_30s",
        "beta_elasticidade":4.19,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 133.05 – R$ 151.95",
        "n_obs_mes":29,
        "r_quadrado_mes":0.85,
        "faixa_praticada_MES_R$_duracao":"R$ 124.30 – R$ 141.96"
    },
    {
        "mes_nome":"Dez",
        "mes_num":12,
        "nome_formato":"Rotativo 07-19H",
        "duracao_segundos":15,
        "produto_chave_original":"rotativo 07-19h_15s",
        "beta_elasticidade":0.0,
        "acao_recomendada":"Manter (Inconclusivo)",
        "faixa_sugerida_R$_duracao":"R$ 94.34 – R$ 94.34",
        "n_obs_mes":26,
        "r_quadrado_mes":0.86,
        "faixa_praticada_MES_R$_duracao":"R$ 88.14 – R$ 88.14"
    }
]